FROM php:8.0-fpm


#RUN apt-get update && apt-get install -y \
#      apt-utils \
#      libpq-dev \
#      libpng-dev \
#      libzip-dev \
#      zip unzip \
#      git && \
#      docker-php-ext-install pdo_mysql && \
#      docker-php-ext-install bcmath && \
#      docker-php-ext-install gd && \
#      docker-php-ext-install zip && \
#      apt-get clean && \
#      rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


# Install composer
#ENV COMPOSER_ALLOW_SUPERUSER=1
#RUN curl -sS https://getcomposer.org/installer | php -- \
#   --filename=composer \
#    --install-dir=/usr/local/bin

RUN docker-php-ext-install pdo mysqli

#COPY --from=composer /usr/bin/composer /usr/bin/composer

COPY ./_docker/php/php.ini /usr/local/etc/php/conf.d/php.ini

# RUN apt-get update && apt-get install -y \
#     git \
#     curl \
#     zip \
#     vim \
#     unzip

WORKDIR /var/www